---
name: "Plugin Issue"
description: "Report a bug or problem with the plugin."
title: "[Plugin Issue] <short description>"
labels: [bug]
body:
  - type: textarea
    id: describe-issue
    attributes:
      label: Describe the Issue
      description: "What happened? What did you expect to happen?"
      placeholder: "Describe the bug or problem in detail."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: "List the steps to reproduce the issue."
      placeholder: "1. ...\n2. ...\n3. ..."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Console Output
      description: 'Paste any error messages or logs here. Logs are located at %userprofile%\.runelite\logs on Windows or $HOME/.runelite/logs on Linux and macOS.'
      placeholder: "Paste logs here."
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Relevant Screenshots
      description: "Add any relevant screenshots to help explain your problem."
      placeholder: "Attach screenshots here."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add any other context about the problem here."
      placeholder: "Other details"
    validations:
      required: false
